// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DatasetProperty {
    name: string;
    value: string;
}

export interface PoolDevice {
    path: string;
}

export interface PoolMirror {
    devices: outputs.PoolMirrorDevice[];
}

export interface PoolMirrorDevice {
    path: string;
}

export interface PoolProperty {
    name: string;
    value: string;
}

