// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Data about a specific dataset.
 */
export function getDataset(args: GetDatasetArgs, opts?: pulumi.InvokeOptions): Promise<GetDatasetResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zfs:index/getDataset:getDataset", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDataset.
 */
export interface GetDatasetArgs {
    /**
     * Name of the zfs dataset.
     */
    name: string;
}

/**
 * A collection of values returned by getDataset.
 */
export interface GetDatasetResult {
    /**
     * gid of the group owning the mountpoint.
     */
    readonly gid: number;
    /**
     * Name of the group owning the mountpoint
     */
    readonly group: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Mountpoint of the dataset.
     */
    readonly mountpoint: string;
    /**
     * Name of the zfs dataset.
     */
    readonly name: string;
    /**
     * Username of the owner of the mountpoint
     */
    readonly owner: string;
    /**
     * Formatted versions of all zfs properties.
     */
    readonly properties: {[key: string]: any};
    /**
     * Parseable versions of all zfs properties.
     */
    readonly rawProperties: {[key: string]: any};
    /**
     * uid of the owner of the mountpoint
     */
    readonly uid: number;
}
/**
 * Data about a specific dataset.
 */
export function getDatasetOutput(args: GetDatasetOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDatasetResult> {
    return pulumi.output(args).apply((a: any) => getDataset(a, opts))
}

/**
 * A collection of arguments for invoking getDataset.
 */
export interface GetDatasetOutputArgs {
    /**
     * Name of the zfs dataset.
     */
    name: pulumi.Input<string>;
}
