// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPool(args: GetPoolArgs, opts?: pulumi.InvokeOptions): Promise<GetPoolResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zfs:index/getPool:getPool", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getPool.
 */
export interface GetPoolArgs {
    /**
     * Name of the zpool.
     */
    name: string;
}

/**
 * A collection of values returned by getPool.
 */
export interface GetPoolResult {
    /**
     * Capacity of the pool.
     */
    readonly capacity: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Name of the zpool.
     */
    readonly name: string;
    /**
     * Formatted versions of all zfs properties.
     */
    readonly properties: {[key: string]: any};
    /**
     * Parseable versions of all zfs properties.
     */
    readonly rawProperties: {[key: string]: any};
    /**
     * Size of the pool.
     */
    readonly size: string;
}
export function getPoolOutput(args: GetPoolOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPoolResult> {
    return pulumi.output(args).apply((a: any) => getPool(a, opts))
}

/**
 * A collection of arguments for invoking getPool.
 */
export interface GetPoolOutputArgs {
    /**
     * Name of the zpool.
     */
    name: pulumi.Input<string>;
}
